version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"